# Generated by Django 5.2.1 on 2025-06-17 20:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('R', 'ROMANCE'), ('C', 'COMEDY'), ('P', 'POLITICS'), ('F', 'FINANCE'), ('T', 'TRAGEDY')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Y', 'YORUBA'), ('I', 'IGBO'), ('H', 'HAUSA'), ('E', 'ENGLISH'), ('F', 'FRENCH'), ('S', 'SPANISH'), ('R', 'RUSSIAN'), ('P', 'PORTUGUESE')], default='E', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('author', models.ManyToManyField(related_name='books', to='user.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.language')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('A', 'AVAILABLE'), ('B', 'BORROWED'), ('M', 'MAINTENANCE')], default='A', max_length=1, unique=True)),
                ('return_date', models.DateTimeField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
