# Generated by Django 5.2.1 on 2025-06-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('A', 'AVAILABLE'), ('B', 'BORROWED'), ('M', 'MAINTENANCE')], default='A', max_length=1),
        ),
    ]
